### BASICS OF NUMPY AND PANDAS LIBRARY :


In [1]:
import numpy as np
import pandas as pd


In [2]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
print(a1)

[1 2 3 4 5]


In [3]:
a1_sqs = a1**2
print(a1_sqs)

[ 1  4  9 16 25]


In [12]:
#arithmetic and trigonometric operations :
print(a1_sqs - a1)
a1_sins = print(np.sin(a1))

a1_sins

[ 0  2  6 12 20]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [15]:
l2 = [[1,2,3],[4,5,6],[7,8,9]]
a2 = np.array(l2)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
#Attributees of an np array
print("dimension :") 
print(a2.ndim)
print("shape :") 
print(a2.shape)
print("size :") 
print(a2.size)
print("data type:") 
print(a2.dtype)

dimension :
2
shape :
(3, 3)
size :
9
data type:
int64


In [29]:
#slicing indexing
print(a2[0,0:3])
print(a2[0:3,0])

[1 2 3]
[1 4 7]


In [30]:
#flatten the array and reshape it 
l3 = [[1,2],[3,4],[5,6],[7,8],[9 ,10],[11,12]]
a3 = np.array(l3)
a3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [31]:
#flattening the array a3:
a3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
a3.shape=(3,4)
a3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
a3.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [41]:
#cross and dot products of matrices
np.dot(a2,a3)
#dot sathi chalta pan cross sathi shape same pahije ?

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])