In [2]:
from sklearn.datasets import load_digits
digits = load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.2,random_state=10)

In [10]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression(solver='liblinear',multi_class='ovr')
log.fit(X_train,y_train)
log.score(X_test,y_test)

0.9583333333333334

In [11]:
from sklearn.svm import SVC
svc = SVC(gamma='auto')
svc.fit(X_train,y_train)
svc.score(X_test,y_test)

0.40555555555555556

In [12]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=50)
rfc.fit(X_train,y_train)
rfc.score(X_test,y_test)

0.9666666666666667

In [15]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [17]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
#     x_train,x_test,y_train,y_test = 
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [36]:
lr_score = []
svm_score = []
rfc_score = []

In [37]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [38]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)

In [39]:
for train_index,test_index in skf.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    lr_score.append(get_score(LogisticRegression(multi_class='ovr',solver='liblinear'),
                              X_train,X_test,y_train,y_test))
    rfc_score.append(get_score(RandomForestClassifier(n_estimators=50),X_train,X_test,y_train,y_test))
    svm_score.append(get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test))

In [46]:
print(lr_score)
print(rfc_score)
print(svm_score)


[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]
[0.925249169435216, 0.9482470784641068, 0.9295302013422819]
[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]


In [ ]:
# cross_val_score function

In [47]:
from sklearn.model_selection import cross_val_score

In [48]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)


array([0.89534884, 0.94991653, 0.90939597])

In [49]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target,cv=3)

array([0.93023256, 0.95158598, 0.92281879])

In [50]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.39368771, 0.41068447, 0.45973154])

In [51]:
# Parameter tunning using k fold cross validation

In [53]:
import numpy as np
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)


0.8858695030503695

In [54]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores1)


0.9433488631751489

In [55]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores1)


0.9533201370249047

In [56]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores1)


0.9516722138961512

In [58]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target, cv=10)
np.average(scores1)



0.946654768079294

In [59]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=45),digits.data, digits.target, cv=10)
np.average(scores1)


0.9511142442435767